load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "go_tutorial",
    srcs = ["greetings.go"],
    importpath = "gitlab.com/hooshi/DSA-practice/go_tutorial",
    visibility = ["//visibility:public"],
)
