load("@rules_python//python:defs.bzl", "py_test")

py_test(
    name = "fb_spiral_array",
    srcs = ["main.py"],
    main = "main.py",
    deps = [
        "@pypi//pytest",
        "@pypi//pytest_timeout",
    ],
)
