load("@rules_python//python:defs.bzl", "py_test")

py_test(
    name = "sortedcontainers",
    srcs = ["sortedcontainers.py"],
    main = "sortedcontainers.py",
    deps = [
        "@pypi//pytest",
        "@pypi//pytest_timeout",
        "@pypi//sortedcontainers",
    ],
)
