name: Merge Checks

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  # so the CI bazel is used.
  CI: "1"

jobs:
  main:

    # This is personal project only tested on macos.
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3

    - uses: bazel-contrib/setup-bazel@0.15.0
      with:
        disk-cache: ${{ github.workflow }}
        bazelisk-cache: true
        repository-cache: true

    - name: Build
      run: ./bazel build ...

    - name: Run static checks
      run: ./m lint

    - name: Test
      run: ./bazel test ...
