name: Merge Checks

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  main:

    # This is personal project only tested on macos.
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3

    - name: Build
      run: ./bazel build ...

    - name: Run static checks
      run: ./m lint

    - name: Test
      run: ./bazel test ...
